name: SweetAdaptiveShop
version: '${version}'
main: top.mrxiaom.sweet.adaptiveshop.SweetAdaptiveShop
api-version: 1.13
depend: [ Vault ]
softdepend:
  - PlaceholderAPI
  - MythicLib
  - MythicMobs
  - ItemsAdder
authors: [ MrXiaoM ]
folia-supported: true
commands:
  sweetadaptiveshop:
    description: 'The main command of SweetAdaptiveShop'
    aliases: [ sashop, sas ]
